config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  get 'users/edit'
  put 'users/update'
  resources :albums
  devise_for :users
  get 'home/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index'
end

app/models/address.rb
class Address < ApplicationRecord
	belongs_to :user
end

app/models/album.rb
class Album < ApplicationRecord
	belongs_to :user

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :albums
  enum gender: %i(male female)
  has_many :addresses

  accepts_nested_attributes_for :addresses , reject_if: proc{ |attributes| attributes['address_line1'].blank? }, allow_destroy: true
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :set_album, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /albums
  # GET /albums.json
  def index
    @albums = current_user.albums
  end

  # GET /albums/1
  # GET /albums/1.json
  def show
  end

  # GET /albums/new
  def new
    @album = Album.new
  end

  # GET /albums/1/edit
  def edit
  end

  # POST /albums
  # POST /albums.json
  def create
    @album = Album.new(album_params)

    respond_to do |format|
      if @album.save
        format.html { redirect_to @album, notice: 'Album was successfully created.' }
        format.json { render :show, status: :created, location: @album }
      else
        format.html { render :new }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /albums/1
  # PATCH/PUT /albums/1.json
  def update
    respond_to do |format|
      if @album.update(album_params)
        format.html { redirect_to @album, notice: 'Album was successfully updated.' }
        format.json { render :show, status: :ok, location: @album }
      else
        format.html { render :edit }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /albums/1
  # DELETE /albums/1.json
  def destroy
    @album.destroy
    respond_to do |format|
      format.html { redirect_to albums_url, notice: 'Album was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_album
      @album = Album.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def album_params
      params.require(:album).permit(:title, :description, :user_id)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = current_user
  end

  def edit
    @user = current_user
    @user.addresses.build
  end

  def update
    @user = current_user
    @user.update(user_params)
    redirect_to users_show_path(@user)
  end

  def user_params
  params.require(:user).permit(:first_name, :last_name, :gender, :date_of_birth, addresses_attributes: [:address_line1, :state, :pincode, :city, :id, :_destroy])
  end 
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/albums/_form.html.erb
<%= form_with(model: album, local: true) do |form| %>
  <% if album.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(album.errors.count, "error") %> prohibited this album from being saved:</h2>

      <ul>
      <% album.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  
  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>


   <%= form.hidden_field :user_id, value: current_user.id %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/albums/edit.html.erb
<h1>Editing Album</h1>

<%= render 'form', album: @album %>

<%= link_to 'Show', @album %> |
<%= link_to 'Back', albums_path %>

app/views/albums/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Albums</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @albums.each do |album| %>
      <tr>
        <td><%= album.title %></td>
        <td><%= album.description %></td>
        <td class="glyphicon glyphicon-folder-open"><%= link_to 'Show', album %></td>
        <td class="glyphicon glyphicon-pencil"><%= link_to 'Edit', edit_album_path(album) %></td>
        <td class="glyphicon glyphicon-trash"><%= link_to 'Destroy', album, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/albums/new.html.erb
<h1>New Album</h1>

<%= render 'form', album: @album %>

<%= link_to 'Back', albums_path , class: 'btn btn-info btn-sm'%>

app/views/albums/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @album.title %>
</p>
<p>
  <strong>Description:</strong>
  <%= @album.description %>
</p>

<%= link_to 'Edit', edit_album_path(@album) %> 
<%= link_to 'Back', albums_path %>

app/views/home/index.html.erb
<body>
<h2 >Welcome to the Gallery</h2>
<p><strong>	Your albums are secured here!</p>
</strong>
</body>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
	<div class="container-fluid">

		<ul class='nav navbar-nav'>
			<li >	<%= link_to 'Add Album', new_album_path  %></li>
			<li > <%= link_to 'My Album', albums_path %></li>
		</ul>

		<ul class="nav navbar-nav navbar-right">
			<li><% if user_signed_in? %>
				<%= link_to current_user.email, users_show_path(current_user) %></li>
				<li><%= link_to 'signout', destroy_user_session_path, method: :delete%></li>
				<% else %>
				<li><%= link_to 'Sign In', new_user_session_path %></li>
				<% end %>
			</ul>

		</div>

	</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= content_for?(:title) ? yield(:title) : "MyAlbum" %></title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag "application", :media => "all" %>

  <%= render 'layouts/header' %>      

  <%= javascript_include_tag "application" %>

  <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
  <![endif]-->
</head>
<body>

  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <%= bootstrap_flash %>
        
        <%= yield %>
      </div>
    </div><br><br><!--/row-->
    <footer>
      
    </footer>
  </div> <!-- /container -->

</body>
</html>

app/views/users/edit.html.haml
%h1 Edit profile
.field
  = link_to 'BackToProfile',users_show_path(@user.id), class: 'pull-right btn btn-success glyphicon glyphicon-arrow-left'
= form_for @user, url:'/users/update', html: {method: :put} do |f|
  .field
    = f.label :first_name
    = f.text_field :first_name
  .field
    = f.label :last_name
    = f.text_field :last_name
  .form-group
    = f.label :gender
    .field
      = f.label :gender, for: 'user_gender_male', class:'check-box-inline' do
        = f.radio_button :gender, :male
        Male
    .field
      = f.label :gender, for: 'user_gender_female', class:'check-box-inline' do
        = f.radio_button :gender, :female
        Female
  .field
    = f.label :date_of_birth
    = f.date_select :date_of_birth

  =f.fields_for :addresses do |address_f|
    %hr
    = address_f.hidden_field :id, value: address_f.object&.id
    .field
      = address_f.label :address_line1
      = address_f.text_field :address_line1

    .field
      = address_f.label :state
      = address_f.text_field :state

    .field
      = address_f.label :pincode
      = address_f.text_field :pincode
    .field
      = address_f.label :city
      = address_f.text_field :city
    .field
      = address_f.label :_destroy do
        = address_f.check_box :_destroy
        Destroy?
    
  .action
    =f.submit 'save'

app/views/users/show.html.haml
%h1 MyProfile

=link_to 'Edit', users_edit_path(@user.id), class: 'pull-right btn btn-danger glyphicon glyphicon-pencil'

%p
  %label First Name
  = @user.first_name

%p
  %label Last Name
  = @user.last_name

%p
  %label Gender
  = @user.gender
%p
  %label Date Of Birth
  = @user.date_of_birth

%p
  %label Address
  -@user.addresses.each do |address_a|
    %p
      = address_a.address_line1
    %p
      = address_a.state
    %p
      = address_a.pincode
    %p
      = address_a.city

app/views/users/update.html.haml
%h1 Users#update
%p Find me in app/views/users/update.html.haml